# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meuprojeto"
BBFILE_PATTERN_meuprojeto = "^${LAYERDIR}/"
BBFILE_PRIORITY_meuprojeto = "6"

# This should only be added to a single layer where it is needed
LAYERSERIES_COMPAT_meuprojeto = "scarthgap"
